name: Publish Package to npmjs
on:
  workflow_dispatch:
  release:
    types: [published]
  push:
    tags:
      - 'v*'

permissions:
  id-token: write  # Required for OIDC
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - uses: actions/setup-node@v7
        with:
          node-version: '24'
          registry-url: 'https://registry.npmjs.org'
          package-manager-cache: false
      - run: yarn install --frozen-lockfile
        working-directory: package
      - run: yarn run copy_publish_files
        working-directory: package
      - run: npm stage publish
        working-directory: package
